name: Dota 2 Basic Stats to Discord

on:
  schedule:
    - cron: '0 18 * * *'  # Diariamente a las 18:00 UTC
  workflow_dispatch:

jobs:
  dota-stats:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install requests beautifulsoup4

    - name: Ejecutar script básico de estadísticas
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        STEAM_IDS: ${{ secrets.STEAM_IDS }}
      run: python scripts/dota_stats_basic.py

    - name: Notificar éxito
      if: success()
      run: echo "Estadísticas básicas enviadas a Discord"
